"""initial migration

Revision ID: bd6f9ab05483
Revises: a01e611fea7e
Create Date: 2025-08-04 14:02:45.389200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd6f9ab05483'
down_revision: Union[str, None] = 'a01e611fea7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_ocr')
    op.add_column('job_ocr', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('job_ocr', 'test_result')
    op.drop_column('job_ocr', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_ocr', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('job_ocr', sa.Column('test_result', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_column('job_ocr', 'created_at')
    op.create_table('test_ocr',
    sa.Column('job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pdf_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ocr_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ocr_result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pdf_page_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_file_path', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('job_id', 'pdf_id', 'ocr_id', name=op.f('test_ocr_pkey'))
    )
    # ### end Alembic commands ###
