"""create job_ocr tables

Revision ID: dbde1ce3e1a8
Revises: 
Create Date: 2025-06-25 17:07:07.660158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbde1ce3e1a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_ocr',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('pdf_id', sa.String(length=64), nullable=False),
    sa.Column('ocr_id', sa.String(length=64), nullable=False),
    sa.Column('ocr_result', sa.Text(), nullable=False),
    sa.Column('pdf_page_num', sa.Integer(), nullable=False),
    sa.Column('image_file_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id', 'pdf_id', 'ocr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_ocr')
    # ### end Alembic commands ###
