"""test_column_add

Revision ID: a01e611fea7e
Revises: f7024c8b4b04
Create Date: 2025-07-31 14:11:37.521412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01e611fea7e'
down_revision: Union[str, None] = 'f7024c8b4b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_ocr', sa.Column('test_result', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_ocr', 'test_result')
    # ### end Alembic commands ###
