"""test_ocr_1

Revision ID: f7024c8b4b04
Revises: dbde1ce3e1a8
Create Date: 2025-07-31 13:39:06.786351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7024c8b4b04'
down_revision: Union[str, None] = 'dbde1ce3e1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_ocr',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('pdf_id', sa.String(length=64), nullable=False),
    sa.Column('ocr_id', sa.String(length=64), nullable=False),
    sa.Column('ocr_result', sa.Text(), nullable=False),
    sa.Column('pdf_page_num', sa.Integer(), nullable=False),
    sa.Column('image_file_path', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id', 'pdf_id', 'ocr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_ocr')
    # ### end Alembic commands ###
